name: Java CI with Maven

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
  
    - name: Rodar
      uses: actions/setup-java@v4
      with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
    
    - name: Rodar testes com Maven
      run: mvn -B test --file teste-unitario-2/pom.xml
    
    - name: Upload relatório de testes
      uses: actions/upload-artifact@v4
      with:
          name: relatorio-testes
          path: teste-unitario-2/target/surefire-reports/
  
  
  build:
    runs-on: ubuntu-latest
    needs: testes
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
  
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
  
    - name: Compilar e empacotar com Maven
      run: mvn -B package --file teste-unitario-2/pom.xml
  
    - name: Upload pacote JAR
      uses: actions/upload-artifact@v4
      with:
        name: pacote-app
        path: teste-unitario-2/target/*.jar
  
  
  notificacao:
    runs-on: ubuntu-latest
    needs: [testes, build]
    steps:
      - name: Instalar mailutils
        run: sudo apt-get update && sudo apt-get install -y mailutils

      - name: Enviar notificação por e-mail
        run: |
          echo "Pipeline executado com sucesso!" | mail -s "Notificação CI/CD" $EMAIL_DESTINO
        env:
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
